/*
 * patch_relocs.c - Patch unsupported ARM relocation types in ELF files
 * 
 * vita-elf-create doesn't support R_ARM_GOTPC (type 25) relocations
 * generated by some pre-compiled libraries (curl, openssl).
 * This tool patches them to R_ARM_NONE (type 0) so vita-elf-create
 * can process the ELF successfully.
 *
 * Usage: patch_relocs <input.elf>
 * Modifies the file in-place.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* ELF32 structures */
typedef struct {
    unsigned char e_ident[16];
    uint16_t e_type, e_machine;
    uint32_t e_version, e_entry, e_phoff, e_shoff;
    uint32_t e_flags;
    uint16_t e_ehsize, e_phentsize, e_phnum;
    uint16_t e_shentsize, e_shnum, e_shstrndx;
} Elf32_Ehdr;

typedef struct {
    uint32_t sh_name, sh_type, sh_flags, sh_addr;
    uint32_t sh_offset, sh_size, sh_link, sh_info;
    uint32_t sh_addralign, sh_entsize;
} Elf32_Shdr;

typedef struct {
    uint32_t r_offset;
    uint32_t r_info;
} Elf32_Rel;

#define SHT_REL  9
#define SHT_RELA 4

#define ELF32_R_TYPE(i)    ((i) & 0xFF)
#define ELF32_R_SYM(i)    ((i) >> 8)
#define ELF32_R_INFO(s,t)  (((s) << 8) | ((t) & 0xFF))

#define R_ARM_NONE  0
#define R_ARM_GOTPC 25

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <elf-file>\n", argv[0]);
        return 1;
    }

    FILE *f = fopen(argv[1], "r+b");
    if (!f) {
        perror("fopen");
        return 1;
    }

    /* Read ELF header */
    Elf32_Ehdr ehdr;
    fread(&ehdr, sizeof(ehdr), 1, f);

    if (memcmp(ehdr.e_ident, "\x7f""ELF", 4) != 0) {
        fprintf(stderr, "Not an ELF file\n");
        fclose(f);
        return 1;
    }

    int patched = 0;

    /* Iterate over section headers */
    for (int i = 0; i < ehdr.e_shnum; i++) {
        Elf32_Shdr shdr;
        fseek(f, ehdr.e_shoff + i * ehdr.e_shentsize, SEEK_SET);
        fread(&shdr, sizeof(shdr), 1, f);

        if (shdr.sh_type != SHT_REL)
            continue;

        /* Process each relocation entry */
        int num_rels = shdr.sh_size / sizeof(Elf32_Rel);
        for (int j = 0; j < num_rels; j++) {
            Elf32_Rel rel;
            long rel_offset = shdr.sh_offset + j * sizeof(Elf32_Rel);
            fseek(f, rel_offset, SEEK_SET);
            fread(&rel, sizeof(rel), 1, f);

            uint32_t type = ELF32_R_TYPE(rel.r_info);
            if (type == R_ARM_GOTPC) {
                uint32_t sym = ELF32_R_SYM(rel.r_info);
                rel.r_info = ELF32_R_INFO(sym, R_ARM_NONE);
                fseek(f, rel_offset, SEEK_SET);
                fwrite(&rel, sizeof(rel), 1, f);
                patched++;
            }
        }
    }

    fclose(f);
    printf("Patched %d R_ARM_GOTPC relocations to R_ARM_NONE\n", patched);
    return 0;
}
